version: '2'

services:
  docker-mongodb:
    image: "mongo:latest"
    ports:
    - 0.0.0.0:27017:27017
  docker-spring-boot-rest:
    image: "maven-springboot"
    build: .
    depends_on:
    - docker-mongodb
    ports:
    - 8080:8080
    environment:
    - TEST=test