version: '3'

services:
  docker-redis:
    image: "redis:alpine"
    ports:
    - 0.0.0.0:6379:6379
  docker-mongodb:
    image: "mongo:latest"
    ports:
    - 0.0.0.0:27017:27017
  docker-spring-boot-rest:
    image: maven-springboot
    build: .
    depends_on:
    - docker-mongodb
    ports:
    - 8080:8080
    environment:
    - TEST=test