version: '3'

services:
  docker-elasticsearch:
    image: "elasticsearch:latest"
  docker-redis:
    image: "redis:alpine"
  docker-mongodb:
    image: mongo:latest
    ports:
    - 0.0.0.0:27017:27017
  docker-spring-boot-rest:
    image: maven-springboot
    build: .
    depends_on:
    - docker-mongodb
    ports:
    - 8080:8080
    environment:
    - DATABASE_HOST=docker-mysql
    - DATABASE_USER=root
    - DATABASE_PASSWORD=root
    - DATABASE_NAME=test
    - DATABASE_PORT=3306